version: "3.9"
services:
  web:
    build: src/
    ports:
      - "9001:9001"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password